### ISSUE TITLE
0 - [MR]: Add help command

### ISSUE THREAD

**Issue by snegurova** [snegurova/project-magicdev#16]
**Tech scope:**
- Create help command which prints all commands list, consider group commands by add, change, search, delete and whatever we have

**Comment by kostinaio** [comment]
Для реалізації переміщення по меню за допомогою стрілок та додавання команди меню до бота, ви можете скористатися бібліотекою curses в Python.

Ось приклад, як ви можете використати curses для створення такого меню:
```
python
Copy code
import curses

def main(stdscr):
    # Вимкнути відображення курсора
    curses.curs_set(0)

    # Задати заголовок меню
    title = "Menu"
    stdscr.addstr(0, curses.COLS // 2 - len(title) // 2, title)

    # Створити список пунктів меню
    menu_items = ["Item 1", "Item 2", "Item 3"]
    current_row = 2

    # Відображення пунктів меню
    for i, item in enumerate(menu_items, start=1):
        x = curses.COLS // 2 - len(item) // 2
        y = current_row + i
        stdscr.addstr(y, x, item)

    stdscr.refresh()

    # Головний цикл обробки вводу
    while True:
        key = stdscr.getch()

        if key == curses.KEY_UP:
            current_row = max(2, current_row - 1)
        elif key == curses.KEY_DOWN:
            current_row = min(len(menu_items) + 1, current_row + 1)
        elif key == curses.KEY_ENTER or key in [10, 13]:
            # Обробка вибору пункту меню
            selected_item = menu_items[current_row - 2]
            stdscr.addstr(curses.LINES - 1, 0, f"Selected: {selected_item}")
            stdscr.refresh()
```
curses.wrapper(main)
Цей код створює просте меню із трьома пунктами, яке можна переміщати за допомогою стрілок вверх та вниз. Коли користувач натискає клавішу Enter, він обирає поточний пункт меню, і виводиться повідомлення про обраний пункт.

Щоб додати це до вашого бота, вам просто потрібно замінити print на ваші функції обробки команд бота.
